[workspace]
resolver = "2"
members = [
    "lib",
    "host",
    "primitives",
    "guests/succinct/prover",
    "guests/risc0", 
    "guests/sgx/prover",
    "guests/sgx/guest",
]



# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3


[workspace.dependencies]
hashbrown = { version = "0.14", features = ["inline-more"] }
revm-primitives = { git = "https://github.com/taikoxyz/revm.git", branch = "unstable", default-features = false }
revm = { git = "https://github.com/taikoxyz/revm.git", branch = "unstable", default-features = false, features = [
    "serde",
] }

# for eip-4844
c-kzg = "1.0.0"
tempfile = "3.8"
