[workspace]
resolver = "2"
members = [
    "lib",
    "host",
    "primitives",
    "guests/sp1/prover",
    "guests/risc0",
    "guests/sgx/prover",
    "guests/sgx/guest",
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3


[workspace.dependencies]
hashbrown = { version = "0.14", features = ["inline-more"] }
revm-primitives = { git = "https://github.com/taikoxyz/revm.git", branch = "unstable", default-features = false }
revm = { git = "https://github.com/taikoxyz/revm.git", branch = "unstable", default-features = false, features = [
    "serde",
] }
sp1-core = { git = "https://github.com/succinctlabs/sp1.git", rev = "cb43fd74b24fad8ed24a4885499159de3680c89f" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "cb43fd74b24fad8ed24a4885499159de3680c89f" }
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", rev = "cb43fd74b24fad8ed24a4885499159de3680c89f" }

# for eip-4844
c-kzg = "1.0.0"
tempfile = "3.8"
