[workspace]
resolver = "2"
members = [
    "lib",
    "host",
    "primitives",
    "provers/sp1/prover",
    "provers/risc0",
    "provers/sgx/prover",
    "provers/sgx/guest",
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3


[workspace.dependencies]
hashbrown = { version = "0.14", features = ["inline-more"] }
revm-primitives = { git = "https://github.com/taikoxyz/revm.git", branch = "fix-ecrecover", default-features = false }
revm = { git = "https://github.com/taikoxyz/revm.git", branch = "fix-ecrecover", default-features = false, features = [
    "serde",
] }
sp1-core = { git = "https://github.com/succinctlabs/sp1.git", rev = "cb43fd74b24fad8ed24a4885499159de3680c89f" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "cb43fd74b24fad8ed24a4885499159de3680c89f" }
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", rev = "cb43fd74b24fad8ed24a4885499159de3680c89f" }

alloy-rlp = { version = "0.3", default-features = false }
alloy-rlp-derive = { version = "0.3", default-features = false }

alloy-core = { version = "0.7.0", default-features = false }
alloy-dyn-abi = { version = "0.7.0", default-features = false }
alloy-json-abi = { version = "0.7.0", default-features = false }
alloy-primitives = { version = "0.7.0", default-features = false }
alloy-sol-types = { version = "0.7.0", default-features = false }

alloy-rpc-types = { git = "https://github.com/brechtpd/alloy", branch = "175" }
alloy-rpc-client = { git = "https://github.com/brechtpd/alloy", branch = "175" }
alloy-consensus = { git = "https://github.com/brechtpd/alloy", branch = "175", features = ["serde"] }
alloy-network = { git = "https://github.com/brechtpd/alloy", branch = "175", features = ["k256"] }
alloy-eips = { git = "https://github.com/brechtpd/alloy", branch = "175", features = ["serde"]  }
alloy-provider = { git = "https://github.com/brechtpd/alloy", branch = "175" }
alloy-transport-http = { git = "https://github.com/brechtpd/alloy", branch = "175" }

# serde
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "3.0" }

# for eip-4844
c-kzg = "1.0.0"
tempfile = "3.8"