[toolchain]
channel = "nightly-2024-01-25"
components = ["clippy", "rustfmt", "rust-src"]
profile = "minimal"


# [toolchain]
# channel = "nightly-2024-02-25"
# components = ["clippy", "rustfmt", "rust-src"]
# profile = "minimal"
