[package]
name = "sgx-guest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0", optional = true}
serde_json ={ version = "1.0", optional = true}
serde_with = {version = "3.4.0", optional = true}
tracing = {version = "0.1", optional = true}
tokio = { version = "^1.23", features = ["full"], optional = true}
bincode = {version = "1.3.3", optional = true}
raiko-lib = { path = "../../../lib", features = ["taiko", "std"] , optional = true}
raiko-primitives = { path = "../../../primitives", features = ["taiko"] , optional = true}


[features]
enable = [
    "raiko-lib",
    "raiko-primitives",
    "serde",
    "serde_json",
    "serde_with",
    "tracing",
    "bincode",
    "tokio",
]