[package]
version = "0.1.0"
name = "sp1-prover"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true, default-features = false, optional = true }
alloy-sol-types = { workspace = true, default-features = false }
serde = { version = "1.0", optional = true}
serde_json = { version = "1.0", optional = true }
raiko-lib = { path = "../../../lib", features = ["taiko", "std"] , optional = true }
sp1-core = { workspace = true, optional = true }
anyhow = {version = "1.0", optional = true }
once_cell = "1.19.0"
sha3 = { version = "0.10", default-features = false}

[build-dependencies]
sp1-helper = { workspace = true, optional = true }

[features]
enable = [
    "serde",
    "serde_json",
    "raiko-lib",
    "sp1-core",
    "anyhow",
    "sp1-helper",
    "alloy-primitives",
]
