[package]
name = "risc0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
zeth-primitives = { path = "../../primitives", features = ["revm"] }
zeth-lib = { path = "../../lib", features = ["taiko"] }
risc0-zkvm = { version = "0.18", default-features = false, features = ["std"] }
