[package]
version = "0.1.0"
name = "sp1-guest"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.6", default-features = false, optional = true }
serde = { version = "1.0", optional = true}
serde_json = { version = "1.0", optional = true }
zeth-lib = { path = "../../../lib", features = ["taiko", "std"] , optional = true }
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" , optional = true }
anyhow = {version = "1.0", optional = true }

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" , optional = true }

[features]
enable = [
    "serde",
    "serde_json",
    "zeth-lib",
    "sp1-core",
    "anyhow",
    "sp1-helper",
    "alloy-primitives",
]
