[package]
name = "raiko-guest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeth-primitives = { path = "../../primitives", features = ["revm"] }
zeth-lib = { path = "../../lib", features = ["taiko", "std"] }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
serde = { version = "1.0.195", features = ["derive"] }