[package]
name = "risc0-methods"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
zeth-primitives = { path = "../../../primitives", features = ["revm"] }
zeth-lib = { path = "../../../lib", features = ["taiko", "std"] }
risc0-zkvm = { version = "0.20.1", default-features = false, features = ['std', "getrandom"] }
ahash = "0.8.6"

[patch.crates-io]
# use optimized risc0 circuit
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }

# DONT do `cargo update` in this package!!! might break r0 build mostly due to compiler requirements on 1.70
# Documented version patch in Carto.toml:
#     - ahash = { version = "0.8.6" }   --> cargo update -p ahash --precise 0.8.6
#     - alloy = { brecht's version }
#     - cargo update bumpalo@3.15.1 --precise 3.14.0
