[package]
name = "harness-core"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "macro"
# path = "src/macro.rs"
# proc-macro = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
once_cell = "1.8.0"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "main", optional = true}

[features]
sp1 = ["dep:sp1-zkvm"]

