[package]
name = "zeth-testeth"
version = "0.1.0"
edition = "2021"

[features]
ef-tests = []

[dependencies]
anyhow = "1.0"
hashbrown = { workspace = true }
revm = { workspace = true }
serde = "1.0"
serde_json = "1.0"
serde_with = "3.1"
zeth-lib = { path = "../../lib" }
zeth-primitives = { path = "../../primitives" }

[dev-dependencies]
diff = "0.1"
env_logger = "0.10"
log = "0.4"
rstest = "0.18"
tempfile = "3.6"

[package.metadata.risc0]
methods = ["testguest"]
