name: CI - All

on:
  push:
    branches: ["main"]
    paths:
      - "host/**"
      - "lib/**"
      - "primitives/**"
      - "script/**"
  pull_request:
    paths:
      - "host/**"
      - "lib/**"
      - "primitives/**"
      - "script/**"
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-native:
    uses: ./.github/workflows/ci-native.yml

  build-test-risc0:
    uses: ./.github/workflows/ci-risc0.yml

  build-test-sp1:
    uses: ./.github/workflows/ci-sp1.yml

  build-test-sgx-all:
    uses: ./.github/workflows/ci-sgx-all.yml

  test-lib:
    name: Test raiko-lib
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - run: cargo test -p raiko-lib --features=std

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: risc0/risc0/.github/actions/rustup@release-0.19

      - uses: risc0/risc0/.github/actions/sccache@release-0.19

      - uses: risc0/clippy-action@main
        with:
          reporter: 'github-pr-check'
          fail_on_error: true
          clippy_flags: --workspace --all-targets --all-features -- -D warnings

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: risc0/risc0/.github/actions/rustup@release-0.19

      - run: make fmt
