name: CI - Native

on: workflow_call


jobs:
    build-test-sgx:
      name: Build and test sgx with Docker
      uses: ./.github/workflows/ci-build-test-reusable.yml
      with:
        version_name: "native"
        version_toolchain: "nightly-2024-04-17"