name: CI - Native

on: workflow_call


jobs:
    build-test-sgx:
      name: Build and test sgx with Docker
      uses: ./.github/workflows/build-test.yml
      with:
        version_name: "native"
        toolchain: "nightly-2024-04-17"