name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_VERSION: 0.20.1
  RISC0_TOOLCHAIN_VERSION: test-release-2

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-risc0:
    name: Build risc0
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
    - run: rustc --version
    - uses: risc0/risc0/.github/actions/sccache@release-0.19
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@v1.6.4
    - run: cargo binstall -y --force cargo-risczero@${{ env.RISC0_VERSION }}
    - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION
    - run: cargo build -p risc0-guest

  build-sp1:
    name: Build sp1
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-01-25
          override: true
          components: clippy, rustfmt, rust-src
      - run: |
          curl -L https://sp1.succinct.xyz | bash && source $HOME/.bashrc && sp1up
      - run: cargo build -p raiko-host --features succinct

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-01-25
          override: true
      - uses: actions-rs/cargo@v1
        with: 
          command: check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: risc0/risc0/.github/actions/rustup@release-0.19
    - uses: risc0/risc0/.github/actions/sccache@release-0.19
    - uses: risc0/clippy-action@main
      with:
        reporter: 'github-pr-check'
        fail_on_error: true
        clippy_flags: --workspace --all-targets --all-features -- -Dwarnings

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: risc0/risc0/.github/actions/rustup@release-0.19
    - run: cargo fmt --all --check
